# -*- coding: utf-8 -*-
"""크롤링 과제(환율)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16yxiWlwNLX_EQrRDp3NxaeCZcwGkCUyA
"""

from bs4 import BeautifulSoup 
from urllib.request import urlopen
import pandas as pd


home='http://finance.naver.com'
url = home+"/marketindex/"
html = urlopen(url)
soup = BeautifulSoup(html, "html.parser")
iframe_src = soup.select_one("#frame_ex1").attrs["src"]
html = urlopen(home+f"{iframe_src}")
soup = BeautifulSoup(html, "html.parser")

table=soup.find("table","tbl_exchange")
tbody=table.find("tbody")
trs=tbody.find_all("tr")

header=["통화명","매매기준율","사실때","파실때","보내실때","받으실때","미화환산율"]
print(header)
result=[]
country=[]
for tr in trs:
    tds=tr.find_all("td")
    data=[]
    for td in tds:
        data.append(td.get_text().strip())
    result.append(data)
    country.append(data[0])
    print(data)
